from typing import Protocol
from uuid import UUID

from domain.entities.booking import Booking
from domain.entities.booking_history import BookingHistory
from domain.entities.office import Office
from domain.entities.meeting_room import MeetingRoom
from domain.entities.user import User


class DBOfficesRepositoryInterface(Protocol):
    async def save(self, office: Office) -> Office: ...
    async def delete_office(self, office: Office) -> None: ...
    async def get_by_id(self, office_id: UUID) -> Office | None: ...
    async def get_all(
        self,
        is_active: bool | None = None,
        city: str | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[Office]: ...


class DBMeetingRoomsRepositoryInterface(Protocol):
    async def save(self, room: MeetingRoom) -> MeetingRoom: ...
    async def delete_room(self, room: MeetingRoom) -> None: ...
    async def get_by_id(self, room_id: UUID) -> MeetingRoom | None: ...
    async def get_all(
        self,
        is_active: bool | None = None,
        office_id: UUID | None = None,
        floor: int | None = None,
        capacity_gte: int | None = None,
        capacity_lte: int | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> list[MeetingRoom]: ...


class DBBookingsRepositoryInterface(Protocol):
    async def save(self, booking: Booking) -> Booking: ...
    async def delete_booking(self, booking: Booking) -> None: ...
    async def get_by_id(self, booking_id: UUID) -> Booking | None: ...
    async def get_all(self) -> list[Booking]: ...


class DBBookingHistorysRepositoryInterface(Protocol):
    async def save(self, booking_history: BookingHistory) -> BookingHistory: ...
    async def delete_booking_history(
        self, booking_history: BookingHistory
    ) -> None: ...
    async def get_by_id(
        self, booking_history_id: UUID
    ) -> BookingHistory | None: ...
    async def get_all(self) -> list[BookingHistory]: ...


class DBUsersRepositoryInterface(Protocol):
    async def save(self, user: User) -> User: ...
    async def delete_user(self, user: User) -> None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_all(self) -> list[User]: ...
