[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "argon2-cffi>=25.1.0",
    "asyncpg>=0.31.0",
    "dishka>=1.10.1",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.136.1",
    "pydantic-settings>=2.14.0",
    "pyjwt>=2.12.1",
    "redis>=7.4.0",
    "sqlalchemy[asyncio]>=2.0.49",
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.ruff]
target-version = "py313"
# Устанавливаем максимальную длину строки для кода
line-length = 80

# Включает нестабильные и находящиеся в предварительной версии правила
preview = true

src = ["src"]

[tool.ruff.lint]
# Выбираем правила, которые должен применять линтер.
select = [
    "A", # flake8-builtins | Выявления случаев, когда имена переменных, аргументов функций или атрибутов классов затеняют встроенные имена Python
    "ANN", # flake8-annotations | Проверка заполненных аннотаций
    "ARG", # flake8-unused-arguments | Выявление неиспользуемых аргументов в функциях, методах, классах, статических методах и лямбда-функциях
    "ASYNC", # flake8-async | Выявление ошибок с асинхронностью
    "B", # flake8-bugbear | Находит общие ошибки и неоднозначности в коде
    "BLE", # flake8-blind-except | Подсказывает, что отлавливать BaseException нельзя
    "C", # flake8-comprehensions | Проверка стилевых ошибок, которые связаны с соглашениями кодирования convention messages
    "COM", # flake8-commas | Проверка наличия запятой в конце строк
    "C4", # flake8-comprehensions | Проверяет правильность и эффективность использования list, set, dict comprehensions
    "C90", # mccabe | Проверка сложности функций
    "DTZ", # flake8-datetimez | Выявление проблем использования объектов даты и времени без учета временных зон
    "E", # pycodestyle errors |
    "ERA", # eradicate | Проверяет наличие закомментированного кода
    "F", # pyflakes | Ошибки, такие как неиспользуемые импорты и переменные
    "FBT", # flake8-boolean-trap | Ошибки при использовании булевых типов в аннотации функций
    "FAST", # fastapi |
    "FURB", # refurb | Выявление и предложение улучшений в коде, связанных с использованием более эффективных, чистых или современных практик программирования
    "I", # isort | Правила для сортировки импортов
    "ICN", # flake8-import-conventions | Соответствие имен при импорте согласно конвенции
    "ISC", # flake8-implicit-str-concat | Проверяет использование неэффективной конкатенации строк
    "N", # pep8-naming | Соблюдение соглашения о наименовании
    "PERF", # perflint | Правила, направленные на выявление потенциальных проблем с производительностью
    "RET", # flake8-return | Ошибки return
    "PIE", # flake8-pie |
    "PL", # Pylint | Правила
    "RUF", # Ruff | Мелочи от Ruff
    "SIM", # flake8-simplify | Проверяет наличие ненужной вложенности нескольких последовательных менеджеров контекста
    "SLF", # flake8-self | Проверяет доступ к «частным» членам класса
    "TCH", # flake8-type-checking | Подсказки по тайпчекингу
    "TD", # flake8-todos | Правила, правильного написания задач
    "T20", # flake8-print | Выявления случаев, использование отладчика в продакшен-коде
    "UP", # pyupgrade | Новых функций языка и замену устаревших конструкций на более эффективные и безопасные аналоги
    "W", # pycodestyle warnings |
]
# Исключаем директории и файлы из линтинга
exclude = [
    ".venv/*",
    "__pycache__",
    ".vscode/*",
    ".git",
    "**/tests/*",
    "tests",
    "**/migrations/*"
]

# Игнорируем конкретные предупреждения линтера
ignore = [
    "B008", # Игнорирование предупреждения от flake8-bugbear, который указывает на проблему использования вызовов любых "вызываемых" объектов в качестве значений аргументов по умолчанию
    "PLR0904", # Максимальное количество методов класса
    "PLR0913", # Максимальное количество аргументов, допустимое для определения функции или метода
    "RUF001", # Игнорирование похожих символов с разными ASCII
    "RUF002", # Игнорирование похожих символов с разными ASCII
    "RUF003", # Игнорирование похожих символов с разными ASCII
    "N818", # Именование исключений с ...Error
    "B024", # наличие у абстрактного класса абстрактных методов
    "ANN003", # типизация kwargs
    "PLR0917", # Максимум позиционных аргументов (новое правило pylint)
    "FBT001", # Boolean-typed positional argument
    "FBT002",
    "TC003" # Move standard library import into a type-checking block
]

# Ошибки, которые могут исправлены автоматически
fixable = [
    "COM",
    "I",
]
